language: node_js
node_js: stable

script: yarn build

branches:
  only: source

deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  on:
    branch: source
